<h1>Edit User</h1>
<hr>
<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PUT">
    <?php if (isset($errors['nickname'])) : ?>
        <p><?= $errors['nickname'] ?></p>
    <?php endif; ?>
    <label for="nickname">Nickname:</label>
    <input type="text" name="user[nickname]" id="nickname" value="<?= htmlspecialchars($user['nickname']) ?>">
    <br>
    <br>
    <?php if (isset($errors['email'])) : ?>
        <p><?= $errors['email'] ?></p>
    <?php endif; ?>
    <label for="email">Email:</label>
    <input type="email" name="user[email]" id="email" value="<?= htmlspecialchars($user['email']) ?>">
    <br>
    <br>
    <button type="submit">Submit</button>    
</form>