<h1>Users</h1>

<form action="/logout" method="post">
    <button type="submit">Logout</button>
</form>

<a href="/users/new">Add new user</a>

<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif; ?>
<hr>
<form method="get">
    <input type="text" name="username" value="<?= htmlspecialchars($username) ?>">
    <button type="submit">Search</button>
    <hr>
    <ul>
        <?php foreach ($users as $user) : ?>
            <li>
                <a href="/users/<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['nickname']) ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</form>